// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-project/app/policy/internal/biz"
	"kratos-project/app/policy/internal/conf"
	"kratos-project/app/policy/internal/data"
	"kratos-project/app/policy/internal/server"
	"kratos-project/app/policy/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDBClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	discovery := data.NewDiscovery(registry)
	importTemplateClient := data.NewImportTemplateClient(discovery)
	dataData, cleanup, err := data.NewData(confData, logger, db, importTemplateClient)
	if err != nil {
		return nil, nil, err
	}
	basePolicyRepo := data.NewBasePolicyRepo(dataData, logger)
	policyUsecase := biz.NewPolicyUsecase(basePolicyRepo, logger)
	importPolicyRepo := data.NewImportPolicyRepo(dataData, logger)
	importPolicyUsecase := biz.NewImportPolicyUsecase(importPolicyRepo, logger)
	policyService := service.NewPolicyService(policyUsecase, importPolicyUsecase)
	httpServer := server.NewHTTPServer(confServer, policyService, logger)
	grpcServer := server.NewGRPCServer(confServer, policyService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
