// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.2.0

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ImportTemplateHTTPServer interface {
	GetPolicy(context.Context, *GetTemplateRequest) (*ImportTemplateStruct, error)
}

func RegisterImportTemplateHTTPServer(s *http.Server, srv ImportTemplateHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/importTemplate/{id}", _ImportTemplate_GetPolicy0_HTTP_Handler(srv))
}

func _ImportTemplate_GetPolicy0_HTTP_Handler(srv ImportTemplateHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTemplateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.importTemplate.v1.ImportTemplate/GetPolicy")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPolicy(ctx, req.(*GetTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ImportTemplateStruct)
		return ctx.Result(200, reply)
	}
}

type ImportTemplateHTTPClient interface {
	GetPolicy(ctx context.Context, req *GetTemplateRequest, opts ...http.CallOption) (rsp *ImportTemplateStruct, err error)
}

type ImportTemplateHTTPClientImpl struct {
	cc *http.Client
}

func NewImportTemplateHTTPClient(client *http.Client) ImportTemplateHTTPClient {
	return &ImportTemplateHTTPClientImpl{client}
}

func (c *ImportTemplateHTTPClientImpl) GetPolicy(ctx context.Context, in *GetTemplateRequest, opts ...http.CallOption) (*ImportTemplateStruct, error) {
	var out ImportTemplateStruct
	pattern := "/v1/importTemplate/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.importTemplate.v1.ImportTemplate/GetPolicy"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
